require 'middleman-gh-pages'

# This seems an odd thing, but doesn't work without it...
ENV["PROJECT_ROOT"]="../slate/"

task :default => [:build]

task :update_docs => [:build] do
  system("cp -r build/* ../api/")
end
