anynines: "/user/deployment-v2/providers/anynines/"
AWS CloudFormation: "/user/deployment-v2/providers/cloudformation/"
AWS CodeDeploy: "/user/deployment-v2/providers/codedeploy/"
AWS Elastic Beanstalk: "/user/deployment-v2/providers/elasticbeanstalk/"
AWS Lambda: "/user/deployment-v2/providers/lambda/"
AWS OpsWorks: "/user/deployment-v2/providers/opsworks/"
AWS S3: "/user/deployment-v2/providers/s3/"
Azure Web Apps: "/user/deployment-v2/providers/azure-web-apps/"
Bintray: "/user/deployment-v2/providers/bintray/"
Bluemix CloudFoundry: "/user/deployment-v2/providers/bluemixcloudfoundry/"
Boxfuse: "/user/deployment-v2/providers/boxfuse/"
Cargo: "/user/deployment-v2/providers/cargo/"
Chef Supermarket: "/user/deployment-v2/providers/chefsupermarket/"
Cloud 66: "/user/deployment-v2/providers/cloud66/"
Cloud Foundry: "/user/deployment-v2/providers/cloudfoundry/"
Convox: "/user/deployment-v2/providers/convox/"
Datica: "/user/deployment-v2/providers/datica/"
Engine Yard: "/user/deployment-v2/providers/engineyard/"
GitHub Pages: "/user/deployment-v2/providers/pages/"
GitHub Releases: "/user/deployment-v2/providers/releases/"
Gleis: "/user/deployment-v2/providers/gleis/"
Google App Engine: "/user/deployment-v2/providers/google-app-engine/"
Google Cloud Storage: "/user/deployment-v2/providers/gcs/"
Google Firebase: "/user/deployment-v2/providers/firebase/"
Hackage: "/user/deployment-v2/providers/hackage/"
Hephy: "/user/deployment-v2/providers/hephy/"
Heroku: "/user/deployment-v2/providers/heroku/"
Launchpad: "/user/deployment-v2/providers/launchpad/"
NPM: "/user/deployment-v2/providers/npm/"
Netlify Drop: "/user/deployment-v2/providers/netlify/"
OpenShift: "/user/deployment-v2/providers/openshift/"
packagecloud: "/user/deployment-v2/providers/packagecloud/"
Puppet Forge: "/user/deployment-v2/providers/puppetforge/"
PyPI: "/user/deployment-v2/providers/pypi/"
Rackspace Cloud Files: "/user/deployment-v2/providers/cloudfiles/"
RubyGems: "/user/deployment-v2/providers/rubygems/"
Scalingo: "/user/deployment-v2/providers/scalingo/"
Script: "/user/deployment-v2/providers/script/"
Snap Store: "/user/deployment-v2/providers/snap/"
Surge.sh: "/user/deployment-v2/providers/surge/"
TestFairy: "/user/deployment-v2/providers/testfairy/"
Transifex: "/user/deployment-v2/providers/transifex/"
